/// Generated by AssetsRefGenerator on 2021/08/18
// ignore_for_file: constant_identifier_names

class Res {
  static const String placeholder = "assets/listing/placeholder.png";
  static const String search = "assets/listing/search.png";

  static const String arrow = "assets/menu/arrow.png";
  static const String e_magazine = "assets/menu/e_magazine.png";
  static const String explore = "assets/menu/explore.png";
  static const String gallery = "assets/menu/gallery.png";
  static const String live = "assets/menu/live.png";
  static const String profile = "assets/menu/profile.png";
  static const String selected = "assets/menu/selected.png";
  static const String wishlist = "assets/menu/wishlist.png";








}
